---
AWSTemplateFormatVersion: "2010-09-09"
Description: This is the first cloudformation template to create S3 bucket and EC2 Instance
Resources:
  VishalEC2Instance:
   Type: AWS::EC2::Instance
   Properties:
     ImageId: ami-0f58b397bc5c1f2e8
     InstanceType: t2.micro
 